apiVersion: apps/v1
kind: Deployment
metadata:
  name: yeslay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yeslay
  template:
    metadata:
      labels:
        app: yeslay
    spec:
      containers:
      - image: okteto.dev/yeslay:latest
        name: yeslay
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "51ape.com"
        - name: Vless_UUID
          value: "a6811c7a-309d-4722-9aed-84ec04c5a02d"
        - name: Vless_Path
          value: "/ohyess"
        - name: Vmess_UUID
          value: "a6811c7a-309d-4722-9aed-84ec04c5a02d"
        - name: Vmess_Path
          value: "/ohmess"
        - name: Share_Path
          value: "/share233"
